<?php

// REMOVES "GENERATED BY WORDPRESS" FROM SOURCE CODE
remove_action('wp_head', 'wp_generator');  

// REMOVES WLPMANIFEST FROM SOURCE CODE
remove_action( 'wp_head', 'wlwmanifest_link');    

// REMOVES SHORTLINK FROM SOURCE CODE
remove_action( 'wp_head', 'wp_shortlink_wp_head');  

// REMOVES XML-RPC FROM SOURCE CODE !!!!!IF 3RD PARTY PLUGINS STOP WORKING THAT USE XML-RPC REQUESTS, ADD BACK IN
remove_action ('wp_head', 'rsd_link');              

//Remove all emoji scripts
remove_action( 'wp_head', 'print_emoji_detection_script', 7 ); 
remove_action( 'wp_print_styles', 'print_emoji_styles' );

/** Disable JSON API **/
add_filter('rest_enabled', '_return_false');
add_filter('rest_jsonp_enabled', '_return_false');

// Disable REST API link tag
remove_action('wp_head', 'rest_output_link_wp_head', 10);

// Disable oEmbed Discovery Links
remove_action('wp_head', 'wp_oembed_add_discovery_links', 10);

// Disable REST API link in HTTP headers
remove_action('template_redirect', 'rest_output_link_header', 11, 0);