<?php

// REMOVES "GENERATED BY WORDPRESS" FROM SOURCE CODE
remove_action('wp_head', 'wp_generator');

// REMOVES WLPMANIFEST FROM SOURCE CODE
remove_action( 'wp_head', 'wlwmanifest_link');

// REMOVES SHORTLINK FROM SOURCE CODE
remove_action( 'wp_head', 'wp_shortlink_wp_head');     

//Remove all emoji scripts
remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
remove_action( 'wp_print_styles', 'print_emoji_styles' );

// Disable REST API link tag
remove_action('wp_head', 'rest_output_link_wp_head', 10);

// Disable oEmbed Discovery Links
remove_action('wp_head', 'wp_oembed_add_discovery_links', 10);
